[options]
  bootstrap_before = "init#before"
  buffer_index_type = 4
  colorscheme = "monochrome"
  background = "dark"
  default_indent = 2
  enable_debug = 0
  enable_guicolors = true
  enable_tabline_filetype_icon = true
  max_column = 100
  github_username = 'hnrck'
  realtime_leader_guide = 1
  statusline_separator = "arrow"
  statusline_iseparator = "bar"
  buffer_index_type = 0
  enable_statusline_mode = false
  statusline_left_sections = [
    'winnr',
    'major mode',
    'filename',
    'fileformat',
    'minor mode lighters',
    'version control info',
    'search status'
  ]
  statusline_right_sections = [
    'cursorpos',
    'percentage',
    'input method',
    'date',
    'time'
  ]
  custom_color_palette = [
    ["#e3e8ea", "#454545", 246, 235],
    ["#e3e8ea", "#5c5c5c", 239, 246],
    ["#e3e8ea", "#454545", 237, 246],
    [           "#686868", 241],
    ["#e3e8ea", "#454545", 235, 109],
    ["#e3e8ea", "#454545", 235, 208],
    ["#e3e8ea", "#454545", 235, 108],
    ["#e3e8ea", "#454545", 235, 72],
    ["#e3e8ea", "#454545", 235, 132],
  ]

[[layers]]
  name = 'autocomplete'
  auto-completion-delay = 10
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = 'VersionControl'
[[layers]]
  name = 'git'

[[layers]]
  name = 'colorscheme'

[[layers]]
  name = 'lang#c'
  [layer.clang_std]
    c = 'c11'
    cpp = 'c++17'
    objc = 'c11'
    objcpp = 'c++17'
[[layers]]
  name = 'lang#latex'
[[layers]]
  name = 'lang#markdown'
[[layers]]
  name = 'lang#toml'
[[layers]]
  name = 'lang#python'
[[layers]]
  name = 'lang#vim'

[[custom_plugins]]
  name = 'rhysd/vim-clang-format'
  name = 'vhdirk/vim-cmake'
  name = 'fxn/vim-monochrome'
