[options]
  bootstrap_before = "init#before"
  buffer_index_type = 4
  colorscheme = "nord"
  background = "dark"
  default_indent = 2
  enable_debug = 0
  enable_guicolors = true
  enable_statusline_display_mode = false
  enable_tabline_filetype_icon = true
  max_column = 100
  github_username = 'hnrck'
  realtime_leader_guide = 1
  statusline_inactive_separator = "arrow"
  statusline_separator = "arrow"

[[layers]]
  name = 'autocomplete'
  auto-completion-delay = 10
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = 'VersionControl'
[[layers]]
  name = 'git'
[[layers]]
  name = 'github'

[[layers]]
  name = 'incsearch'
[[layers]]
  name = 'ctrlp'

[[layers]]
  name = 'colorscheme'

[[layers]]
  name = 'lsp'

[[layers]]
  name = 'lang#c'
  clang_executable = '/usr/home/h.deschamps/.local/clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-16.04/bin/clang'
  libclang_path = '/usr/home/h.deschamps/.local/clang+llvm-7.0.0-x86_64-linux-gnu-ubuntu-16.04/lib/'
  [layer.clang_std]
    c = 'c11'
    cpp = 'c++17'
    objc = 'c11'
    objcpp = 'c++17'
[[layers]]
  name = 'lang#elixir'
[[layers]]
  name = 'lang#haskell'
[[layers]]
  name = 'lang#latex'
[[layers]]
  name = 'lang#markdown'
[[layers]]
  name = 'lang#toml'
[[layers]]
  name = 'lang#python'
[[layers]]
  name = 'lang#xml'
[[layers]]
  name = 'lang#vim'

[[custom_plugins]]
  name = 'eagletmt/ghcmod-vim'
  name = 'bitc/vim-hdevtools'
  name = 'Twinside/vim-hoogle'
  name = 'rhysd/vim-clang-format'
  name = 'vhdirk/vim-cmake'
  name = 'arecarn/vim-selection'
  name = 'rhysd/vim-grammarous'
  name = 'tyrannicaltoucan/vim-deep-space'
  name = 'icymind/NeoSolarized'
#name = 'arcticicestudio/nord-vim'
#name = 'severin-lemaignan/vim-minimap'
